# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Steward < Formula
  desc "AI Personal Assistant — single binary, multi-provider, voice-enabled"
  homepage "https://github.com/brooqs/steward"
  version "1.2.9"
  license "MIT"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brooqs/steward/releases/download/v1.2.9/steward_1.2.9_darwin_amd64.tar.gz"
      sha256 "772919c238f3eeeed8ae0cb4308e6e7a69fa6edec75389682b15a35ab4f210bf"

      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brooqs/steward/releases/download/v1.2.9/steward_1.2.9_darwin_arm64.tar.gz"
      sha256 "b671cec76864d59b949a9b1a3df6dd8f358990275313e0015cf8f6613963606c"

      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brooqs/steward/releases/download/v1.2.9/steward_1.2.9_linux_amd64.tar.gz"
      sha256 "e16e94e31bc72cc06c93891862b0d1240955a82f3718070ba7419424a6ed09b3"
      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brooqs/steward/releases/download/v1.2.9/steward_1.2.9_linux_arm64.tar.gz"
      sha256 "28f0181371b056e23e6d91a7096aa7feb7bf33d3e3fd64f545adbcbf9a02dd1e"
      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started:
        1. cp #{etc}/steward/core.yml.example #{etc}/steward/core.yml
        2. Edit #{etc}/steward/core.yml with your provider and API key
        3. brew services start steward
        4. Open http://localhost:8080 for the admin panel

      WhatsApp bridge installed at: #{libexec}/bridge/whatsapp
        Start: node #{libexec}/bridge/whatsapp/index.js
    EOS
  end

  service do
    run [opt_bin/"steward", "-config", etc/"steward/core.yml"]
    keep_alive true
    log_path var/"log/steward.log"
    error_log_path var/"log/steward.err"
  end
end
