# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Steward < Formula
  desc "AI Personal Assistant — single binary, multi-provider, voice-enabled"
  homepage "https://github.com/brooqs/steward"
  version "1.3.2"
  license "MIT"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brooqs/steward/releases/download/v1.3.2/steward_1.3.2_darwin_amd64.tar.gz"
      sha256 "1c973da8838422898945209c41a8ef0f2513c34318cb0669416e206d57812e41"

      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brooqs/steward/releases/download/v1.3.2/steward_1.3.2_darwin_arm64.tar.gz"
      sha256 "b603a1ad7856d5c726fedd174b633d6658a93c501f353f42bebd535b388454f6"

      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brooqs/steward/releases/download/v1.3.2/steward_1.3.2_linux_amd64.tar.gz"
      sha256 "932c8c52d3765510396aac6cc8d732b3a416e794619381d5114a48c8ce7c01b2"
      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brooqs/steward/releases/download/v1.3.2/steward_1.3.2_linux_arm64.tar.gz"
      sha256 "46ba35553444d7452b68180c0efdebeba0223e47d60efcf95cd6f87a4b884c48"
      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started:
        1. cp #{etc}/steward/core.yml.example #{etc}/steward/core.yml
        2. Edit #{etc}/steward/core.yml with your provider and API key
        3. brew services start steward
        4. Open http://localhost:8080 for the admin panel

      WhatsApp bridge installed at: #{libexec}/bridge/whatsapp
        Start: node #{libexec}/bridge/whatsapp/index.js
    EOS
  end

  service do
    run [opt_bin/"steward", "-config", etc/"steward/core.yml"]
    keep_alive true
    log_path var/"log/steward.log"
    error_log_path var/"log/steward.err"
  end
end
