# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Steward < Formula
  desc "AI Personal Assistant — single binary, multi-provider, voice-enabled"
  homepage "https://github.com/brooqs/steward"
  version "1.4.2"
  license "MIT"

  depends_on "node"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brooqs/steward/releases/download/v1.4.2/steward_1.4.2_darwin_amd64.tar.gz"
      sha256 "08ede926034c15d17425983a9f2ad20d072e340d3c37e5b0489c08b749bcab0e"

      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brooqs/steward/releases/download/v1.4.2/steward_1.4.2_darwin_arm64.tar.gz"
      sha256 "c376b8fe713a1f944102feb44b977a28b0f121cbcd540fe372501154e9024bfa"

      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/brooqs/steward/releases/download/v1.4.2/steward_1.4.2_linux_amd64.tar.gz"
      sha256 "452365d736c8902f9942b32824c65bd96e3f670ea4b5f310db4dbf356cf9fc19"
      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/brooqs/steward/releases/download/v1.4.2/steward_1.4.2_linux_arm64.tar.gz"
      sha256 "12b31d6550d4d2907e3eb333c9e7f3a288f1d371222b595c5a7f1a57320039a8"
      define_method(:install) do
        bin.install "steward"
        bin.install "steward-satellite"

        # Create config directory
        (etc/"steward").mkpath
        (etc/"steward/integrations").mkpath
        etc.install "config/core.yml.example" => "steward/core.yml.example"

        # Create data directory
        (var/"lib/steward").mkpath

        # Install WhatsApp bridge
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/index.js"
        (libexec/"bridge/whatsapp").install "bridge/whatsapp/package.json"
        cd libexec/"bridge/whatsapp" do
          system "npm", "install", "--production"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started:
        1. cp #{etc}/steward/core.yml.example #{etc}/steward/core.yml
        2. Edit #{etc}/steward/core.yml with your provider and API key
        3. brew services start steward
        4. Open http://localhost:8080 for the admin panel

      WhatsApp bridge installed at: #{libexec}/bridge/whatsapp
        Start: node #{libexec}/bridge/whatsapp/index.js
    EOS
  end

  service do
    run [opt_bin/"steward", "-config", etc/"steward/core.yml"]
    keep_alive true
    log_path var/"log/steward.log"
    error_log_path var/"log/steward.err"
  end
end
